spring:
  application:
    name: fintech-banking
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: '@Rancho.dev'
    driver-class-name: org.postgresql.Driver

  mail:
    username: deep041999@gmail.com
    password: omkrydlcovltlcay
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    error:
      whitelabel:
        enabled: true

server:
  address: 127.0.0.1
  port: 8899

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000   # 1 day in ms